### ISSUE TITLE
No sound played: Could not get response for the request LoadRequest

### ISSUE THREAD

**Issue by bigboss97** [roblatour/Cast#1]
I've cast v1.4 on a Windows 7 PC and it's working perfectly. Now I'm trying v1.8 (also v1.4) on my Windows 10 laptop and I'm getting this:
```
PS C:\Program Files\Cast> .\Cast.exe -debug -text hello
Start inventory devices - first attempt
Wait time = 00:00:03
Google device count = 1
        Living Room display
End inventory devices - first attempt

*snip*
Casting "hello"

Streaming will begin at 9/04/2022 4:16:06 PM
StartWebServer 9/04/2022 4:16:03 PM
Start Listen 9/04/2022 4:16:03 PM
Casting to Living Room display C:\Users\home\AppData\Local\Temp\~cast~95374625cc944178a81f4d0c1f0a03cc.wav
Casting to METABOX-I7 C:\Users\home\AppData\Local\Temp\~cast~95374625cc944178a81f4d0c1f0a03cc.wav
Preparing to cast C:\Users\home\AppData\Local\Temp\~cast~d74864584b19406294a5b581da8da636.wav
********* Go: 04/09/2022 04:16:06.5462 PM
Preparing to play on speakers C:\Users\home\AppData\Local\Temp\~cast~95374625cc944178a81f4d0c1f0a03cc.wav
Duration: 00:00:01.2790000
System.TimeoutException: Could not get response for the request LoadRequest
   at SharpCast.Channel.SendRequest(String ns, Request request, String destinationId) in E:\Documents\VBNet\cast\SharpCast\Channel.cs:line 144
   at SharpCast.Player.Load(Uri contentUri, String contentType, MediaMetadata metadata, Boolean autoPlay, StreamType streamType) in E:\Documents\VBNet\cast\SharpCast\Player.cs:line 98
   at cast.modCasting.VB$StateMachine_5_CastAFile.MoveNext() in E:\Documents\VBNet\cast\cast\modCasting.vb:line 112
Duration: 00:00:01.2790000
Casting complete
```
I can find the generated WAV file. But what does following mean?
```
System.TimeoutException: Could not get response for the request LoadRequest
   at SharpCast.Channel.SendRequest(String ns, Request request, String destinationId) in E:\Documents\VBNet\cast\SharpCast\Channel.cs:line 144
   ```
  I can't find that at all. Is something missing on this laptop?
  Thanks for any help in advance.

**Comment by roblatour** [comment]
looks like it is not connecting to your device to do the cast

can you try casting to a specific ip address and see if that works?

for example:

cast -ip 192.168.200.150 -text hello there

**Comment by Noah-Wilderom** [comment]
Iam having the same issue, getting the same result with ip

**Comment by roblatour** [comment]
can you ping the target ip ok?

**Comment by Noah-Wilderom** [comment]
Ping works fine, i figured out a other way how to TTS on google home and that worked with same device.
